server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/omaralzuhairi27/configuration-yml


management:
  endpoints:
    web:
      exposure:
        include: "*"